### ISSUE TITLE
Example for insertRecords

### ISSUE THREAD

**Issue by davidpeirs** [tristanjahier/zoho-crm-php#4]
Dear,

great work , thanks but i keep getting issues with 
Attempted to call an undefined method named "insertRecord" of class "Zoho\CRM\Api\Modules\Leads".

could you please include an example for inserting.

Sincerly,

David.

ps : beer will be delivered next time i'm in Paris ;)

**Comment by mharacewiat** [comment]
Try to use `insert()` or `insertMany()` directly. It's defined in abstract `AbstractRecordsModule`.

**Comment by tristanjahier** [comment]
Hello @davidpeirs!

Can you please provide the code that produces this error?

I need to rewrite `README.md` completely but, as @Haru0 said, you must use the `insert` or `insertMany` methods. e.g.:

```php
$zoho->leads->insert([
    'Property 1' => 'Value 1',
    'Property 2' => 'Value 2',
]);
```

or

```php
$theLead = new Zoho\CRM\Entities\Lead([
    'Property 1' => 'Value 1',
    'Property 2' => 'Value 2',
]);

$zoho->leads->insert($theLead);
```

**Comment by davidpeirs** [comment]
it is solved ! Thank you so much for the quick response. @Haru0 & @tristanjahier  Your module is great and the tip to fully check the Abstract was very helpfull. Thanks. David.

**Comment by tristanjahier** [comment]
Glad to hear that! 👍
